module.exports = Object.freeze({
  MODAL_BODY_TYPES: {
    GAME_ADD: 'GAME_ADD',
    GAME_INFO: 'GAME_INFO',
    GAME_UPDATE: 'GAME_UPDATE',
    CONFIRMATION: 'CONFIRMATION',
    DEFAULT: '',
  },

  RIGHT_DRAWER_TYPES: {
    NOTIFICATION: 'NOTIFICATION',
    CALENDAR_EVENTS: 'CALENDAR_EVENTS',
  },

  CONFIRMATION_MODAL_CLOSE_TYPES: {
    LEAD_DELETE: 'LEAD_DELETE',
    GAME_DELETE: 'GAME_DELETE',
    GAME_DECLINE: 'GAME_DECLINE',
    GAME_APPROVE: 'GAME_APPROVE',
    GAME_CONCLUDE: 'GAME_CONCLUDE',
    HISTORY_DELETE: 'HISTORY_DELETE',
    HISTORY_CLAIM: 'HISTORY_CLAIM',
  },

  AUTH_ACTIONTYPES: {
    ADMIN_LOGINED: 'ADMIN_LOGINED',
    INVALID: 'INVALID',
  },
})
